using System;
using System.Collections.Generic;

namespace BioinformaticsAlgorithms
{
    public static class Program
    {
        private static void Main(string[] args)
        {
            ITasksSolver solver = new DnaStringTaskSolver();

            string text = "GCGCG";
            const string Pattern = "GCG";
            int patternCount = solver.PatternCount(text, Pattern);
            Console.WriteLine($"PatternCount: {patternCount}");

            text = "CAAGGCAGACAAGGCAGAGTGGCAACGCAAGGCAGACAAGGCAGAGGGGGTAACTACTCCGACCATTTTTGTGGCAACGGGGGGTAACGGGGGTAACTACTCCGATACTCCGATACTCCGACCATTTTTGGGGGTAACCCATTTTTGTGGCAACGCCATTTTTTACTCCGAGTGGCAACGCAAGGCAGACAAGGCAGATACTCCGACCATTTTTGTGGCAACGCCATTTTTCAAGGCAGAGGGGGTAACCCATTTTTTACTCCGAGTGGCAACGGGGGGTAACCCATTTTTCAAGGCAGAGTGGCAACGGGGGGTAACGGGGGTAACCAAGGCAGAGGGGGTAACGGGGGTAACCAAGGCAGACCATTTTTGTGGCAACGTACTCCGACAAGGCAGAGTGGCAACGCCATTTTTCAAGGCAGAGTGGCAACGGTGGCAACGCAAGGCAGACAAGGCAGACCATTTTTGGGGGTAACCCATTTTTCCATTTTTCAAGGCAGAGGGGGTAACGGGGGTAACCAAGGCAGAGGGGGTAACGTGGCAACGCAAGGCAGACAAGGCAGATACTCCGAGTGGCAACGTACTCCGATACTCCGATACTCCGATACTCCGACCATTTTTCAAGGCAGATACTCCGACAAGGCAGAGTGGCAACGGTGGCAACGGGGGGTAACGGGGGTAACCAAGGCAGATACTCCGACCATTTTTGTGGCAACGGTGGCAACGGTGGCAACGTACTCCGAGGGGGTAACTACTCCGACCATTTTTGGGGGTAACCAAGGCAGATACTCCGAGTGGCAACGCAAGGCAGACCATTTTTGGGGGTAACCAAGGCAGAGTGGCAACGTACTCCGAGGGGGTAACGGGGGTAACCAAGGCAGA";
            const int K = 13;
            IEnumerable<string> words = solver.FrequentWords(text, K);
            Console.WriteLine($"FrequentWords: {string.Join(", ", words)}");
        }
    }
}
